@startuml
class ScriptSigFactory {
+createSig_API()
+createSig_Event()
{static} -__type_name : string | "ScriptSigFactory"
-__ctor()
-__dtor()
}
class ScriptSigDispatcher {
-_sigs_cache : map
-_script_listen_map : map
-_script_manager : IScriptManager[weak]
-_unlistenSig()
{static} -__type_name : string | "ScriptSigDispatcher"
-__dtor()
-_listenSig()
-_setScriptManager()
+sendSig()
-__ctor()
+tick()
{static} -__super : IScriptSigDispatcher
}
IScriptSigDispatcher <|-- ScriptSigDispatcher 
ScriptSigDispatcher --> map
ScriptSigDispatcher ..> IScriptManager : weak
class ScriptManager {
-_script_map : map
-_sig_dispatcher : IScriptSigDispatcher[weak]
-_active_script : Script[weak]
+abortScript()
-_scriptWait()
-_setSigDispatcher()
-__dtor()
+scriptIsActive()
+scriptIsRunning()
-__ctor()
-_runScript()
+runScript()
-_getScriptListeningSig()
-_awakeScript()
-_handleScriptAwakeArgs()
-_unsetActiveScript()
{static} -__super : IScriptManager
-_scriptOnSig()
-_setActiveScript()
-_abortScript()
-_handleScriptTickResult()
-_sleepScript()
+loadScript()
{static} -__type_name : string | "ScriptManager"
}
IScriptManager <|-- ScriptManager 
ScriptManager --> map
ScriptManager ..> IScriptSigDispatcher : weak
ScriptManager ..> Script : weak
class ScriptAPIManager {
-_forbid_post_api : boolean | false
-_waiting_sig_logic : IScriptSigLogic
-_sig_factory : ScriptSigFactory[weak]
-_script_manager : IScriptManager[weak]
-_api_dispatcher : IScriptAPIDispatcher[weak]
-_script_api_space : unmanaged
-_api_proxy_map : unmanaged
-_built_in_apiIsExecuting()
{static} -__type_name : string | "ScriptAPIManager"
-_built_in_apiIsDead()
-_built_in_apiAbort()
-_waitSig()
-_registerBuiltInAPI()
-_built_in_apiIsPending()
-__ctor()
+registerAPI()
-_callAPI()
+registerAssistAPI()
-_built_in_apiGetTimeSpent()
-_built_in_waitEvent()
-_built_in_apiGetReturn()
-_built_in_waitCondition()
-_built_in_apiDiedOfInterruption()
-_built_in_apiWait()
-_built_in_delay()
+getAPISpace()
}
ScriptAPIManager --> IScriptSigLogic
ScriptAPIManager ..> ScriptSigFactory : weak
ScriptAPIManager ..> IScriptManager : weak
ScriptAPIManager ..> IScriptAPIDispatcher : weak
class Script {
-_name : string | ""
-_thread : ScriptThread
-_proc : unmanaged
{static} -__type_name : string | "Script"
+sleep()
-__dtor()
+awake()
+abort()
+isActive()
-__ctor()
+run()
+isRunning()
}
Script --> ScriptThread
class IScriptSigLogic {
+is_time_out : boolean | false
{static} -__type_name : string | "IScriptSigLogic"
-__ctor()
+checkTimeOut()
+check()
}
class IScriptAPIDispatcher {
+apiAbort()
+apiIsExecuting()
+apiGetTimeSpent()
{static} -__type_name : string | "IScriptAPIDispatcher"
+apiDiedOfInterruption()
+postAPI()
+apiGetReturn()
+apiIsDead()
-__ctor()
+tick()
+apiIsPending()
}
class map {
-_et_type : number | 0
-_kt : string | ""
-_m : unmanaged
-_et : unmanaged
+isEmpty()
{static} -__type_name : string | "map"
-__dtor()
+containKey()
-_next()
+set()
+clear()
-__ctor()
+pairs()
+get()
}
class ScriptSystem {
-_api_dispatcher : IScriptAPIDispatcher
-_sig_factory : ScriptSigFactory
-_script_manager : ScriptManager
-_sig_dispatcher : ScriptSigDispatcher
-_api_manager : ScriptAPIManager
+registerAPI()
+abortScript()
+runScript()
+loadScript()
{static} -__type_name : string | "ScriptSystem"
-__dtor()
+registerAssistAPI()
+scriptIsRunning()
+sendSig_Event()
-__ctor()
+tick()
+sendSig_API()
}
ScriptSystem --> IScriptAPIDispatcher
ScriptSystem --> ScriptSigFactory
ScriptSystem --> ScriptManager
ScriptSystem --> ScriptSigDispatcher
ScriptSystem --> ScriptAPIManager
class IScriptSigDispatcher {
-_setScriptManager()
-_unlistenSig()
{static} -__type_name : string | "IScriptSigDispatcher"
-__ctor()
-_listenSig()
}
class apiTestNumber {
+num : number | 0
{static} -__super : IAPISample
+getReturn()
+execute()
{static} -__type_name : string | "apiTestNumber"
-__ctor()
}
IAPISample <|-- apiTestNumber 
class SSL_Condition {
-_time_spent : number | 0
-_time_out : number | -1
-_condition : unmanaged
{static} -__super : IScriptSigLogic
+checkTimeOut()
{static} -__type_name : string | "SSL_Condition"
-__ctor()
-__dtor()
+check()
}
IScriptSigLogic <|-- SSL_Condition 
class SSL_Event {
-_time_spent : number | 0
-_time_out : number | -1
-_event_logic_func : unmanaged
{static} -__super : IScriptSigLogic
+checkTimeOut()
{static} -__type_name : string | "SSL_Event"
-__ctor()
-__dtor()
+check()
}
IScriptSigLogic <|-- SSL_Event 
class array {
-_et_type : number | 0
-_a : unmanaged
-_et : unmanaged
+size()
+clear()
{static} -__type_name : string | "array"
+pushFront()
-__dtor()
+peekBack()
+peekFront()
+popFront()
+popBack()
+set()
+pushBack()
-__ctor()
+insert()
+get()
}
class apiTestString {
+str : string | ""
{static} -__super : IAPISample
+getReturn()
+execute()
{static} -__type_name : string | "apiTestString"
-__ctor()
}
IAPISample <|-- apiTestString 
class ScriptThread {
-_co : unmanaged
+start()
-_startRunning()
{static} -__type_name : string | "ScriptThread"
+sleep()
-__dtor()
-_log()
+awake()
-_handleResumeResult()
+abort()
-_endRunning()
-_handleYieldResule()
-__ctor()
+isActive()
+isRunning()
}
class SSL_Timing {
-_time_spent : number | 0
-_time : number | 0
{static} -__super : IScriptSigLogic
+checkTimeOut()
{static} -__type_name : string | "SSL_Timing"
-__ctor()
-__dtor()
+check()
}
IScriptSigLogic <|-- SSL_Timing 
class IAPISample {
+status : number | 0
+post_time : number | 0
{static} -__type_name : string | "IAPISample"
+getReturn()
+execute()
}
class APIDispatcherSample {
-_time : number | 0
-_api_map : map
-_api_token_list : array
-_script_sys : ScriptSystem[weak]
+apiAbort()
+apiIsExecuting()
+apiGetTimeSpent()
{static} -__type_name : string | "APIDispatcherSample"
+apiDiedOfInterruption()
-__dtor()
{static} -__super : IScriptAPIDispatcher
+apiGetReturn()
+apiIsDead()
+apiIsPending()
-__ctor()
+tick()
+postAPI()
}
IScriptAPIDispatcher <|-- APIDispatcherSample 
APIDispatcherSample --> map
APIDispatcherSample --> array
APIDispatcherSample ..> ScriptSystem : weak
class SSL_API {
-_time_out : number | -1
-_api_token : number | 0
-_sig : string | ""
-_api_dispatcher : IScriptAPIDispatcher[weak]
{static} -__super : IScriptSigLogic
+checkTimeOut()
{static} -__type_name : string | "SSL_API"
-__ctor()
-__dtor()
+check()
}
IScriptSigLogic <|-- SSL_API 
SSL_API ..> IScriptAPIDispatcher : weak
class IScriptManager {
-_scriptOnSig()
-_getScriptListeningSig()
-_scriptWait()
-_setSigDispatcher()
{static} -__type_name : string | "IScriptManager"
-__ctor()
}
@enduml